scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
          - localhost:9090
  - job_name: graphite-exporter
    static_configs:
      - targets: 
          - graphite-exporter:9108
